"""The dependency manifest, and the JCL join that closes its ddnames."""

import importlib.util
import json
import sys
from pathlib import Path

from eztrieve_dependencies.parser import parse_eztrieve
from eztrieve_dependencies.views import (bind_jcl_ddnames, build_eztrieve_artifacts,
                                         jcl_steps_running)

EXAMPLES = Path(__file__).resolve().parents[1] / "examples"
FIXTURES = Path(__file__).resolve().parent / "fixtures"
MACROS = {p.stem.upper(): p.read_text(encoding="utf-8")
          for p in EXAMPLES.glob("*.mac")}


def _artifacts(name: str, resolver=None):
    program = parse_eztrieve((EXAMPLES / name).read_text(encoding="utf-8"),
                             resolver=resolver, source_name=name)
    return build_eztrieve_artifacts(program)


def _by_name(manifest):
    return {a["artifact"]: a for a in manifest["artifacts"]}


def _payroll_jcl_lineage():
    """A committed jcl-dependencies LINEAGE view, as a FIXTURE rather than one built live.

    This package must not depend on the JCL one - they are peers - so the JCL model arrives
    as data, which is what it actually is: a schema contract between two distributions that
    release separately. Regenerated by tools/refresh_fixture.py, which fails loudly if the
    shape has drifted, so the two learn about a schema change from a red test rather than
    from a quietly unbound manifest.
    """
    return json.loads((FIXTURES / "payroll.jcl.lineage.json").read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- #
# the manifest
# --------------------------------------------------------------------------- #

def test_a_file_row_is_a_ddname_and_says_it_still_needs_the_jcl():
    """Easytrieve names only the ddname. Reporting it as though it were a dataset identity
    would be the one lie this whole family of tools exists to avoid."""
    row = _by_name(_artifacts("payroll.ezt"))["PERSNL"]
    assert row["kind"] == "file" and row["dependency"] == "runtime"
    assert row["ddname"] == "PERSNL" and row["io"] == "read"
    assert row["identity"] == "program-local"
    assert row["resolvedBy"] == "JCL DD statement"
    assert "the DSN is not knowable from this source alone" in row["needs"]
    assert row["fields"] == 5 and row["recordLength"] == 150


def test_a_file_row_records_which_activities_touched_it_and_how():
    row = _by_name(_artifacts("custupd.ezt"))["CUSTMAST"]
    assert row["io"] == "read-write"
    hows = {(t["how"], t.get("operation")) for t in row["touchedBy"]}
    assert ("POINT", None) in hows and ("GET", None) in hows
    assert ("WRITE", "UPDATE") in hows


def test_a_macro_is_a_compile_time_artifact_and_an_unresolved_one_says_the_model_is_short():
    blind = _by_name(_artifacts("macroed.ezt"))
    assert blind["CUSTREC"]["kind"] == "macro"
    assert blind["CUSTREC"]["dependency"] == "compile-time"
    assert blind["CUSTREC"]["status"] == "unresolved"
    assert blind["CUSTREC"]["usedAt"][0]["arguments"] == ["1"]

    seeing = _by_name(_artifacts("macroed.ezt", resolver=MACROS.get))
    assert seeing["CUSTREC"]["status"] == "expanded"


def test_called_programs_and_file_exits_are_program_rows_with_their_role():
    art = _by_name(_artifacts("custupd.ezt"))
    assert art["AUDITLOG"]["kind"] == "program" and art["AUDITLOG"]["role"] == "called"
    assert art["TRANEDIT"]["role"] == "file exit"
    assert art["TRANEDIT"]["exitFor"] == ["TRANS"]
    assert "can change any field of TRANS" in art["TRANEDIT"]["needs"]


def test_reports_virtual_files_and_instream_tables_are_excluded_with_the_reason():
    excluded = {e["name"]: e for e in _artifacts("custupd.ezt")["excluded"]}
    assert excluded["CODETAB"]["kind"] == "instream-table"
    assert "in this source member" in excluded["CODETAB"]["reason"]

    excluded = {e["name"]: e for e in _artifacts("payroll.ezt")["excluded"]}
    assert excluded["PAYRPT"]["kind"] == "report"
    assert "goes to the run's SYSPRINT" in excluded["PAYRPT"]["reason"]

    program = parse_eztrieve("FILE W VIRTUAL\n  A 1 5 N\n", source_name="f.ezt")
    excluded = {e["name"]: e for e in build_eztrieve_artifacts(program)["excluded"]}
    assert excluded["W"]["kind"] == "virtual-file"


def test_an_sql_statement_contributes_its_tables_but_not_its_columns():
    program = parse_eztrieve(
        "DEFINE WS-ACCT W 8 A\n"
        "JOB INPUT NULL\n"
        "  SQL SELECT ACCT_NO INTO :WS-ACCT FROM GLDB.TRANSACTIONS\n",
        source_name="f.ezt")
    manifest = build_eztrieve_artifacts(program)
    row = _by_name(manifest)["GLDB.TRANSACTIONS"]
    assert row["kind"] == "db2-table" and row["dependency"] == "runtime"
    assert "not which columns it touches" in row["needs"]
    assert any("COLUMN-to-host-field mapping" in f for f in manifest["flags"])


def test_the_manifest_is_ordered_deterministically():
    order = [(a["kind"], a["artifact"]) for a in _artifacts("custupd.ezt")["artifacts"]]
    assert order == sorted(order, key=lambda r: ({"file": 0, "db2-table": 1, "program": 2,
                                                  "macro": 3}[r[0]], r[1]))


# --------------------------------------------------------------------------- #
# the join
# --------------------------------------------------------------------------- #

def test_the_committed_jcl_fixture_still_has_the_shape_the_binder_reads():
    """The cross-repository contract, checked here so drift is a RED TEST rather than a
    quietly unbound manifest - which looks exactly like a manifest nobody tried to bind."""
    spec = importlib.util.spec_from_file_location(
        "refresh_fixture", Path(__file__).resolve().parents[1] / "tools"
        / "refresh_fixture.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["refresh_fixture"] = module
    spec.loader.exec_module(module)
    assert module.check() == []


def test_the_step_is_found_by_its_sysin_member_not_by_its_exec_pgm():
    """Both steps run EZTPA00 - the Easytrieve interpreter - so the step's program name
    cannot say which Easytrieve program runs. The SYSIN member can, and does."""
    lineage = _payroll_jcl_lineage()
    assert jcl_steps_running("PAYROLL", lineage) == ["RUNPAY"]
    assert jcl_steps_running("AUDITRPT", lineage) == ["RUNAUD"]
    assert jcl_steps_running("NOSUCH", lineage) == []


def test_binding_closes_the_ddname_to_dataset_chain():
    out = bind_jcl_ddnames(_artifacts("payroll.ezt"), _payroll_jcl_lineage())
    assert out["jclBinding"]["steps"] == ["RUNPAY"]
    assert out["jclBinding"]["boundFiles"] == 2
    row = _by_name(out)["PERSNL"]
    assert row["dataset"] == "PROD.HR.PERSNL.MASTER"
    assert row["identity"] == "global"
    assert row["resolvedBy"] == "JCL DD statement: PAYRUN.RUNPAY"
    assert "needs" not in row                      # the identity chain is closed
    assert row["boundBy"][0]["step"] == "RUNPAY"


def test_binding_carries_a_gdg_generation_across():
    out = bind_jcl_ddnames(_artifacts("payroll.ezt"), _payroll_jcl_lineage())
    assert _by_name(out)["PAYEXT"]["boundBy"][0]["generation"] == "+1"


def test_binding_to_the_wrong_step_is_what_naming_the_step_prevents():
    """RUNAUD reads a different dataset through the SAME ddname. Bound from that step, the
    answer would be confidently wrong - which is why the step is identified, not assumed."""
    out = bind_jcl_ddnames(_artifacts("payroll.ezt"), _payroll_jcl_lineage(),
                           steps=["RUNAUD"])
    assert _by_name(out)["PERSNL"]["dataset"] == "TEST.HR.PERSNL.SAMPLE"


def test_conflicting_bindings_list_candidates_and_flag_never_collapse():
    """The same ddname bound to different datasets across the supplied steps is a FACT -
    the program runs against different data in different steps - and picking one silently
    would be a lie."""
    out = bind_jcl_ddnames(_artifacts("payroll.ezt"), _payroll_jcl_lineage(),
                           steps=["RUNPAY", "RUNAUD"])
    row = _by_name(out)["PERSNL"]
    assert "dataset" not in row
    assert row["datasetCandidates"] == ["PROD.HR.PERSNL.MASTER", "TEST.HR.PERSNL.SAMPLE"]
    assert len(row["boundBy"]) == 2
    assert any("2 different datasets" in f for f in out["flags"])


def test_an_unidentifiable_step_binds_on_ddname_alone_and_says_so():
    out = bind_jcl_ddnames(_artifacts("custupd.ezt"), _payroll_jcl_lineage())
    assert out["jclBinding"]["steps"] == []
    assert "ddname alone" in out["jclBinding"]["basis"]
    assert any("bound from the wrong step" in f for f in out["flags"])


def test_a_compiled_program_execed_by_name_is_matched_directly():
    lineage = {"format": "jcl-dependencies-lineage", "job": "J", "source": "j.jcl",
               "steps": [], "ddBindings": [
                   {"program": "PAYROLL", "step": "S1", "ddname": "PERSNL",
                    "dataset": "PROD.HR.PERSNL.MASTER", "io": "input"}]}
    out = bind_jcl_ddnames(_artifacts("payroll.ezt"), lineage)
    assert "compiled load module" in out["jclBinding"]["basis"]
    assert _by_name(out)["PERSNL"]["dataset"] == "PROD.HR.PERSNL.MASTER"


def test_binding_does_not_mutate_the_input_manifest():
    manifest = _artifacts("payroll.ezt")
    bind_jcl_ddnames(manifest, _payroll_jcl_lineage())
    row = _by_name(manifest)["PERSNL"]
    assert "dataset" not in row and "needs" in row


def test_an_unmatched_ddname_is_left_honestly_unresolved():
    out = bind_jcl_ddnames(_artifacts("custupd.ezt"), _payroll_jcl_lineage(),
                           steps=["RUNPAY"])
    row = _by_name(out)["CUSTMAST"]
    assert "dataset" not in row and "needs" in row


# --------------------------------------------------------------------------- #
# Db2 SYNONYM/ALIAS: a table row written under a synonym names its base table
# --------------------------------------------------------------------------- #

from mainframe_artifacts.synonyms import SynonymLookup                  # noqa: E402

SQL_PROGRAM = (
    "DEFINE WS-ACCT W 8 A\n"
    "FILE ACCTS SQL SELECT ACCT_NO FROM V_SMIX_ACTIVE\n"
    "JOB INPUT NULL\n"
    "  SQL SELECT ACCT_NO INTO :WS-ACCT FROM RTAC_ACCOUNT\n"
    "  SQL SELECT ACCT_NO INTO :WS-ACCT FROM GLDB.TRANSACTIONS\n")


class _Recorder:
    def __init__(self, answers=None, raises=None):
        self.answers, self.raises, self.calls = answers or {}, raises, []

    def __call__(self, name):
        self.calls.append(name)
        if self.raises is not None:
            raise self.raises
        return self.answers.get(name)


def _tables(manifest):
    return {r["artifact"]: r for r in manifest["artifacts"] if r["kind"] == "db2-table"}


def test_a_synonym_map_stamps_the_base_table_and_leaves_the_name_as_written():
    program = parse_eztrieve(SQL_PROGRAM, source_name="f.ezt")
    rows = _tables(build_eztrieve_artifacts(
        program, synonyms=SynonymLookup({"RTAC_ACCOUNT": "T_RTAC_ACCOUNT"})))
    assert rows["RTAC_ACCOUNT"]["baseTable"] == "T_RTAC_ACCOUNT"
    assert rows["RTAC_ACCOUNT"]["resolvedVia"] == "synonym map"
    assert "baseTable" not in rows["GLDB.TRANSACTIONS"]
    assert "baseTable" not in rows["V_SMIX_ACTIVE"]


def test_the_resolver_answers_what_the_map_does_not_and_is_asked_once_per_table():
    program = parse_eztrieve(SQL_PROGRAM, source_name="f.ezt")
    r = _Recorder({"V_SMIX_ACTIVE": "MMD1DBO.T_SMIX_ACTIVE"})
    rows = _tables(build_eztrieve_artifacts(
        program, synonyms=SynonymLookup({"RTAC_ACCOUNT": "T_RTAC_ACCOUNT"}, r)))
    assert rows["V_SMIX_ACTIVE"]["baseTable"] == "MMD1DBO.T_SMIX_ACTIVE"
    assert rows["V_SMIX_ACTIVE"]["resolvedVia"] == "catalog resolver"
    assert rows["RTAC_ACCOUNT"]["resolvedVia"] == "synonym map"
    assert "baseTable" not in rows["GLDB.TRANSACTIONS"]
    # every table this view names is the point of need - except one the map holds
    assert sorted(r.calls) == ["GLDB.TRANSACTIONS", "V_SMIX_ACTIVE"]


def test_a_resolver_returning_none_leaves_the_manifest_byte_identical():
    program = parse_eztrieve(SQL_PROGRAM, source_name="f.ezt")
    plain = build_eztrieve_artifacts(program)
    asked = build_eztrieve_artifacts(program, synonyms=SynonymLookup(None, _Recorder()))
    assert json.dumps(asked, sort_keys=True) == json.dumps(plain, sort_keys=True)


def test_a_raising_resolver_is_flagged_once_and_no_table_is_stamped():
    program = parse_eztrieve(SQL_PROGRAM, source_name="f.ezt")
    r = _Recorder(raises=RuntimeError("catalog down"))
    manifest = build_eztrieve_artifacts(program, synonyms=SynonymLookup(None, r))
    assert not any("baseTable" in row for row in _tables(manifest).values())
    catalog = [f for f in manifest["flags"] if "synonym resolver failed" in f]
    assert len(catalog) == 1 and "RuntimeError: catalog down" in catalog[0]
    assert len(r.calls) == 1                # disabled after the first failure


def test_the_manifest_conforms_to_the_written_core():
    """Upstream ledger batch 10, item 31: the shared row vocabulary is written down in
    mainframe-artifacts, so this package checks itself against the contract rather than
    against the COBOL and JCL packages' prose."""
    from mainframe_artifacts.manifest import validate_manifest

    for path in sorted(EXAMPLES.glob("*")):
        if path.is_dir():
            continue
        program = parse_eztrieve(path.read_text(encoding="utf-8"),
                                 resolver=MACROS.get, source_name=path.name)
        assert validate_manifest(build_eztrieve_artifacts(program)) == [], path.name
