"""The reverse direction: what depends on what this program provides.

An Easytrieve program says which bytes of which record become which bytes of which other
record. It cannot say which job runs it, or which downstream work reads the data it
writes - those live in an estate index only the host can read - so the answer arrives
through a door and is reported as given.

It also cannot say WHAT it writes, in any name the estate would recognise: a FILE names a
**ddname**, which is program-local. So the written half of this view is asked about as the
DATASET a JCL DD statement binds that ddname to, and with no binding supplied it is
reported unanswerable rather than asked about under a name that exists nowhere outside
this source.
"""

import json
from pathlib import Path

from mainframe_artifacts.dependents import DependentsLookup

from eztrieve_dependencies.api import analyze
from eztrieve_dependencies.parser import parse_eztrieve
from eztrieve_dependencies.views import (FORMAT_DEPENDENTS, bind_jcl_ddnames,
                                         build_eztrieve_artifacts,
                                         build_eztrieve_dependents)

EXAMPLES = Path(__file__).resolve().parents[1] / "examples"
FIXTURES = Path(__file__).resolve().parent / "fixtures"
SOURCE = (EXAMPLES / "payroll.ezt").read_text(encoding="utf-8")

#: What the committed JCL fixture binds PAYEXT to. This is the name the estate knows this
#: program's output by, and it is the SAME name jcl-dependencies asks about for the same
#: DD - so one index answers both packages with one row.
PAYEXT_DSN = "PROD.FIN.PAY.EXTRACT"

#: What a host index holds: a job runs PAYROLL, and one job reads the dataset it writes.
_INDEX = {
    "PAYROLL|program": [
        {"name": "PAYRUN", "kind": "JOB", "via": "EXEC PGM=EZTPA00 SYSIN",
         "match_strength": "qualified", "detail": "step EZT names PAYROLL as SYSIN"},
    ],
    PAYEXT_DSN + "|dataset": [
        {"name": "PAYPOST", "kind": "JOB", "via": "DD DSN=... DISP=SHR",
         "match_strength": "qualified"},
    ],
}


def _program(name="payroll.ezt"):
    return parse_eztrieve((EXAMPLES / name).read_text(encoding="utf-8"), source_name=name)


def _jcl():
    """The committed jcl-dependencies LINEAGE view, as data - this package never imports
    the JCL one. Regenerated by tools/refresh_fixture.py."""
    return json.loads((FIXTURES / "payroll.jcl.lineage.json").read_text(encoding="utf-8"))


def _bound(program=None, lineage=None, steps=()):
    """This program's manifest with the JCL bound into it - what gives a written ddname a
    name that exists outside the program."""
    program = program or _program()
    return bind_jcl_ddnames(build_eztrieve_artifacts(program),
                            _jcl() if lineage is None else lineage, steps=steps)


def _view(mapping=None, resolver=None, bound=None, program=None):
    program = program or _program()
    return build_eztrieve_dependents(program, DependentsLookup(mapping, resolver),
                                     bound=bound)


def _row(view, name):
    return next(r for r in view["provides"] if r["name"] == name)


def _asks(bound=None, program=None):
    """Every (name, kind) the lookup was handed, in order."""
    asked = []

    def index(name, kind=None):
        asked.append((name, kind))
        return []

    _view(resolver=index, bound=bound, program=program)
    return asked


# --- what is asked about --------------------------------------------------------------

def test_the_program_and_the_dataset_it_writes_are_what_is_asked_about():
    # PERSNL is READ, so it is not asked about: that is what this program depends on.
    assert _asks(_bound()) == [("PAYROLL", "program"), (PAYEXT_DSN, "dataset")]


def test_a_bare_ddname_is_never_what_the_estate_is_asked_about():
    """With no binding there is no name to ask about. Asking anyway would match the
    spelling PAYEXT in every program that happens to use it, and a wrong edge in the
    reverse direction is worse than a missing one."""
    assert _asks() == [("PAYROLL", "program")]


def test_an_unbound_ddname_is_unanswerable_by_this_package_not_dropped():
    view = _view(_INDEX)
    assert [r["name"] for r in view["provides"]] == ["PAYROLL"]
    entry, = view["unanswered"]
    assert (entry["name"], entry["kind"], entry["asked"]) == ("PAYEXT", "file", False)
    assert "program-local" in entry["reason"]
    assert "JCL DD statement" in entry["needs"]


def test_the_dataset_asked_about_is_the_one_the_jcl_binds_the_ddname_to():
    """The join is bind_jcl_ddnames', not a second one written for this view - and the
    name it yields is the DSN as the JCL lineage spells it, which is what makes an index
    answer this package and jcl-dependencies identically for the same DD."""
    binding, = [b for b in _jcl()["ddBindings"]
                if b["ddname"] == "PAYEXT" and b["step"] == "RUNPAY"]
    assert _asks(_bound())[1] == (binding["dataset"], "dataset")


def test_dependents_attach_to_the_name_that_was_asked_about():
    view = _view(_INDEX, bound=_bound())
    assert [d["name"] for d in _row(view, "PAYROLL")["dependents"]] == ["PAYRUN"]
    row = _row(view, PAYEXT_DSN)
    assert [d["name"] for d in row["dependents"]] == ["PAYPOST"]
    # The ddname is kept beside the dataset: it is how this program refers to it, and
    # without it a reader cannot tie the row back to the FILE statement.
    assert row["ddname"] == "PAYEXT"
    assert row["provides"] == ("written as ddname PAYEXT, bound to this dataset by "
                               "PAYRUN.RUNPAY")
    assert _row(view, "PAYROLL")["dependents"][0]["matchStrength"] == "qualified"


def test_the_view_has_the_family_keys_and_the_program_subject_key():
    view = _view(_INDEX)
    assert list(view) == ["format", "formatVersion", "program", "source", "note",
                          "suppliedBy", "provides", "unanswered", "flags"]
    assert (view["format"], view["program"]) == (FORMAT_DEPENDENTS, "PAYROLL")


def test_a_bound_run_says_which_job_and_step_the_datasets_came_from():
    view = _view(_INDEX, bound=_bound())
    assert list(view).index("jclBinding") == list(view).index("suppliedBy") + 1
    assert view["jclBinding"]["job"] == "PAYRUN"
    assert view["jclBinding"]["steps"] == ["RUNPAY"]
    assert "SYSIN member" in view["jclBinding"]["basis"]


def test_rows_are_sorted_so_the_hosts_order_cannot_change_the_bytes():
    two = {PAYEXT_DSN + "|dataset": [{"name": "ZLAST", "kind": "JOB"},
                                     {"name": "AFIRST", "kind": "JOB"}]}
    flipped = {PAYEXT_DSN + "|dataset": list(reversed(two[PAYEXT_DSN + "|dataset"]))}
    assert json.dumps(_view(two, bound=_bound())) == \
        json.dumps(_view(flipped, bound=_bound()))


# --- the honesty rules the binding already applies, holding through this view ----------

def test_a_ddname_bound_to_two_datasets_is_asked_about_once_per_dataset():
    """The same ddname bound to different datasets across the supplied steps is a fact -
    the program writes different data in different steps - and collapsing it to one here
    would undo the rule the binding just applied one view earlier."""
    lineage = _jcl()
    lineage["ddBindings"].append(
        {"program": "EZTPA00", "step": "RUNAUD", "ddname": "PAYEXT",
         "dataset": "TEST.FIN.PAY.EXTRACT", "io": "output"})
    bound = _bound(lineage=lineage, steps=["RUNPAY", "RUNAUD"])

    assert _asks(bound) == [("PAYROLL", "program"),
                            ("PROD.FIN.PAY.EXTRACT", "dataset"),
                            ("TEST.FIN.PAY.EXTRACT", "dataset")]
    view = _view(_INDEX, bound=bound)
    row = _row(view, PAYEXT_DSN)
    assert row["datasetCandidates"] == ["PROD.FIN.PAY.EXTRACT", "TEST.FIN.PAY.EXTRACT"]
    assert row["provides"].endswith("bound to this dataset by PAYRUN.RUNPAY")
    assert any("2 different datasets" in f for f in view["flags"])


def test_a_binding_made_on_ddname_alone_is_flagged_here_too():
    """CUSTUPD is not the SYSIN member of any step in this job, so no step could be
    identified - and a dataset bound from another step's ddname would be confidently
    wrong. The artifacts view says so; so must this one, because these rows are asks."""
    program = _program("custupd.ezt")
    view = _view(_INDEX, bound=_bound(program), program=program)
    assert any("made on ddname alone" in f for f in view["flags"])


# --- the three answers ----------------------------------------------------------------

def test_no_lookup_supplied_is_no_view_at_all():
    program = _program()
    assert build_eztrieve_dependents(program, None) is None
    assert build_eztrieve_dependents(program, DependentsLookup()) is None
    # ... and a binding does not make one appear: a run nobody told anything reports
    # nothing about the estate, whatever else it was given.
    assert build_eztrieve_dependents(program, DependentsLookup(),
                                     bound=_bound(program)) is None


def test_a_name_the_index_does_not_cover_is_unanswered_not_empty():
    view = _view({"PAYROLL|program": _INDEX["PAYROLL|program"]}, bound=_bound())
    assert [r["name"] for r in view["provides"]] == ["PAYROLL"]
    assert view["unanswered"] == [
        {"name": PAYEXT_DSN, "kind": "dataset", "ddname": "PAYEXT",
         "reason": "the lookup does not cover this name"}]


def test_asked_and_nothing_depends_on_it_is_said_with_an_empty_list():
    view = _view(resolver=lambda name, kind=None: [], bound=_bound())
    assert _row(view, PAYEXT_DSN)["dependents"] == []
    assert view["unanswered"] == []


def test_a_lookup_that_breaks_is_flagged():
    def boom(name, kind=None):
        raise RuntimeError("index unreachable")

    view = _view(resolver=boom, bound=_bound())
    assert view["provides"] == []
    assert "index unreachable" in view["flags"][0]


def test_a_reported_fan_out_cap_reaches_the_view():
    def capped(name, kind=None):
        return ({"rows": _INDEX[PAYEXT_DSN + "|dataset"], "truncated": True, "total": 77}
                if name == PAYEXT_DSN else None)

    row = _row(_view(resolver=capped, bound=_bound()), PAYEXT_DSN)
    assert (row["truncated"], row["total"]) == (True, 77)


# --- through analyze() and the bundle -------------------------------------------------

def test_analyze_without_the_parameter_is_the_run_it_always_was():
    analysis = analyze(SOURCE, source_name="payroll.ezt", retrieve=False)
    assert analysis.dependents_lookup is None
    assert analysis.dependents() is None
    assert analysis.bound_artifacts() is None


def test_analyze_binds_before_it_asks():
    """The view is built eagerly inside analyze because BUILDING it is what asks the
    host. A binding handed over afterwards would be too late to change what was asked."""
    asked = []

    def index(name, kind=None):
        asked.append((name, kind))
        return []

    analyze(SOURCE, source_name="payroll.ezt", retrieve=False,
            dependents_resolver=index, jcl_lineage=_jcl())
    assert asked == [("PAYROLL", "program"), (PAYEXT_DSN, "dataset")]


def test_the_artifacts_view_and_the_dependents_view_share_one_binding():
    analysis = analyze(SOURCE, source_name="payroll.ezt", retrieve=False,
                       dependents=_INDEX, jcl_lineage=_jcl())
    assert analysis.bound_artifacts() is analysis.bound_artifacts()
    row, = [a for a in analysis.bound_artifacts()["artifacts"]
            if a.get("ddname") == "PAYEXT"]
    assert row["dataset"] == _row(analysis.dependents(), PAYEXT_DSN)["name"]


def test_a_gathered_bundle_replays_the_reverse_direction(tmp_path):
    from mainframe_artifacts.bundle import open_bundle

    from eztrieve_dependencies.api import gather

    def index(name, kind=None):
        return _INDEX.get("{0}|{1}".format(name, kind))

    live = analyze(SOURCE, source_name="payroll.ezt", retrieve=False,
                   dependents_resolver=index, jcl_lineage=_jcl()).dependents()
    root = tmp_path / "bundle"
    gather(SOURCE, source_name="payroll.ezt", dest=str(root),
           dependents_resolver=index, jcl_lineage=_jcl())

    bundle = open_bundle(root)
    assert bundle.has_dependents()
    replayed = analyze(bundle.source(), source_name="payroll.ezt", bundle=bundle,
                       jcl_lineage=_jcl()).dependents()
    assert replayed == live
    assert [r["name"] for r in replayed["provides"]] == ["PAYROLL", PAYEXT_DSN]
